{"name": "Нельзя войти с неверным логином(email)", "status": "passed", "start": 1715188976967, "stop": 1715188977852, "uuid": "6a5a0abb-17c8-46e6-9517-b2ea2c210459", "historyId": "a3cf656949f525d0436d1732b8269e9b", "testCaseId": "a3cf656949f525d0436d1732b8269e9b", "fullName": "tests.test_login.TestLogin#test_login_with_invalid_email_not_completed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-9RKVCCS"}, {"name": "thread", "value": "6656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}